def pop_sent():
    sent = [
[ 0,"It is|a consistent that every part|p of the large house is|a white and the door is|g a|r part|p of the large house and the door is|a white"],
[ 1,"It is|a consistent that I saw everyone who drank something in the van and Leibniz drank something in the van and I saw Leibniz"],
[ 2,"It is|a consistent that I love nothing which is|r about murder and hamlet is|r about murder and I do not love Hamlet"],
[ 3,"It is|a consistent that I love anything which is|r about logic and set theory is|r about logic and I love set theory"],
[ 4,"It is|a consistent that no green man from|b cold Mars, lives on|r Earth and Jim is|g a|r green man born|p on|r Mars and Jim does not live on|r Earth"],
[ 5,"It is|a consistent that every green man from|b Mars drinks and Jim is|g a|r green man born|p on|r Mars and Jim drinks"],
[ 6,"It is|a consistent that everyone who spies on Leibniz, will|r be|a rewarded and Russell spied on Leibniz and Russell was|a rewarded"],
[ 7,"It is|a consistent that everyone who spies on a nazi in Munich, will|r be|a rewarded and Russell spied on a nazi in Munich and Russell was|a rewarded"],
[ 8,"It is|a consistent that anyone who breaks the speed limit, will|r be|a caught and marilyn broke the speed limit and marilyn was|a caught"],
[ 9,"It is|a consistent that I did not shed a tear and I did not shed some|p tears"],
[ 10,"It is|a consistent that every woman at|p the party drank and Jessica was|r at|p the party and Jessica is|g a|r woman and Jessica drank"],
[ 11,"It is|a consistent that every woman at|p the party drank and Jessica was|g a|r woman at|p the party and Jessica drank"],
[ 12,"It is|a consistent that no part|p of the large house is|a white and the door is|g a|r part|p of the large house and the door is|a not white"],
[ 13,"It is|a consistent that I love everyone who reads Leibniz and Russell reads Leibniz and I love Russell"],
[ 14,"It is|a consistent that there is|e a moment which exists in|b time"],
[ 15,"It is|a consistent that no whole|c is|g an|r individual"],
[ 16,"It is|a consistent that there is|e a whole which is|g not an|r individual"],
[ 17,"It is|a consistent that my dog drank some water and I own a dog"],
[ 18,"It is|a consistent that I saw my dog and I own a dog"],
[ 19,"It is|a consistent that I saw your dog and you do own a dog"],
[ 20,"It is|a consistent that your dog drank some water and you do own a dog"],
[ 21,"It is|a consistent that I saw his dog and he owns a dog"],
[ 22,"It is|a consistent that his dog drank some water and he owns a dog"],
[ 23,"It is|a consistent that I took the dog's ball and the dog owns a ball"],
[ 24,"It is|a consistent that the dog's ball is|a red and the dog owns a ball"],
[ 25,"It is|a consistent that Ada's ball is|a red and Ada owns a ball"],
[ 26,"It is|a consistent that I took Ada's ball and Ada owns a ball"],
[ 27,"It is|a consistent that the|r property|n redness is|a not red"],
[ 28,"It is|a consistent that plato has|t the same teacher as Xenothon and Xenothon has|t a teacher"],
[ 29,"It is|a consistent that I did not shed any|n tears and I shed no tears"],
[ 30,"It is|a consistent that no thought smells"],
[ 31,"It is|a consistent that no thought desires something"],
[ 32,"It is|a consistent that there is|e a mind which is|a mental"],
[ 33,"It is|a contradictory that no thought is|g a|r group"],
[ 34,"It is|a consistent that no mind smells"],
[ 35,"It is|a consistent that JFK is|g a|r Kennedy and JFK is|g part|f of the Kennedy|a family"],
[ 36,"It is|a consistent that something is|g a|r cake and cake is|g a|r class"],
[ 37,"It is|a consistent that Russell has|c|r the|r causal role can hit and the|r causal role can hit is|g a|r property|n"],
[ 38,"It is|a consistent that a universal is|r distinct from its|a instance"],
[ 39,"It is|a consistent that there is|e a universal which is|r distinct from its|a instances"],
[ 40,"It is|a consistent that the|r concept|n cat is|g not a|r cat"],
[ 41,"It is|a consistent that dog is|g a|r concept|n"],
[ 42,"It is|a consistent that point is|g not a|r partially material|a concept|n"],
[ 43,"It is|a consistent that this dog is|g not a|r concept|n"],
[ 44,"It is|a consistent that thought is|g not a|r partially material|a concept|n"],
[ 45,"It is|a consistent that every number|i does not smells"],
[ 46,"It is|a consistent that every thought is|a mental|b"],
[ 47,"It is|a consistent that no thought is|g a|r moment"],
[ 48,"It is|a consistent that no thought thinks something"],
[ 49,"It is|a consistent that I do not have a point"],
[ 50,"It is|a consistent that plato has|t the same teacher as Xenothon and that|d teacher is Socrates and socrates teaches Xenothon"],
[ 51,"It is|a consistent that I saw the same movie as you and that|d movie was Casablanca and I saw Casablanca"],
[ 52,"It is|a consistent that Leibniz and|c Aristotle ate from the same cake and this|n was that|d cake and Leibniz ate from this|n"],
[ 53,"It is|a consistent that the door is|a not large and the door which is|a green is|a not large"],
[ 54,"It is|a consistent that Leibniz and|c Aristotle studied logic  and Leibniz studied logic"],
[ 55,"It is|a consistent that Russell is|g a|r man"],
[ 56,"It is|a consistent that Russell has the|r property|n courage  and Russell is|a courageous"],
[ 57,"It is|a consistent that Russell has courage  and Russell is|a courageous"],
[ 58,"It is|a consistent that this cat is|g a|r cat"],
[ 59,"It is|a consistent that JFK is|g a|r Kennedy and JFK is|g part|f of the Kennedy|a family"],
[ 60,"It is|a contradictory that every part|p of the large house is|a white and the door is|g a|r part|p of the large house and the door is|a not white"],
[ 61,"It is|a contradictory that I saw everyone who drank something in the van and Leibniz drank something in the van and I did not see Leibniz"],
[ 62,"It is|a contradictory that I love nothing which is|r about murder and hamlet is|r about murder and I love Hamlet"],
[ 63,"It is|a contradictory that I love anything which is|r about logic and set theory is|r about logic and I do not love set theory"],
[ 64,"It is|a contradictory that no green man from|b cold Mars, lives on|r Earth and Jim is|g a|r green man born|p on|r Mars and Jim lives on|r Earth"],
[ 65,"It is|a contradictory that every green man from|b Mars drinks and Jim is|g a|r green man born|p on|r Mars and Jim does not drink"],
[ 66,"It is|a contradictory that everyone who spies on Leibniz, will|r be|a rewarded and Russell spied on Leibniz and Russell was|a not rewarded"],
[ 67,"It is|a contradictory that everyone who spies on a nazi in Munich, will|r be|a rewarded and Russell spied on a nazi in Munich and Russell was|a not rewarded"],
[ 68,"It is|a contradictory that anyone who breaks the speed limit, will|r be|a caught and marilyn broke the speed limit and marilyn was|a not caught"],
[ 69,"It is|a contradictory that I did not shed a tear and I shed some|p tears"],
[ 70,"It is|a contradictory that every woman at|p the party drank and Jessica was|r at|p the party and Jessica is|g a|r woman and Jessica did not drink"],
[ 71,"It is|a contradictory that every woman at|p the party drank and Jessica was|g a|r woman at|p the party and Jessica did not drink"],
[ 72,"It is|a contradictory that no part|p of the large house is|a white and the door is|g a|r part|p of the large house and the door is|a white"],
[ 73,"It is|a contradictory that I love everyone who reads Leibniz and Russell reads Leibniz and I do not love Russell"],
[ 74,"It is|a contradictory that there is|e a moment which does not exist in|b time"],
[ 75,"It is|a contradictory that there is|e a whole|c which is|g an|r individual"],
[ 76,"It is|a consistent that there is|e a whole which is|g an|r individual"],
[ 77,"It is|a contradictory that my dog drank some water and I do not own a dog"],
[ 78,"It is|a contradictory that I saw my dog and I do not own a dog"],
[ 79,"It is|a contradictory that I saw your dog and you do not own a dog"],
[ 80,"It is|a contradictory that your dog drank some water and you do not own a dog"],
[ 81,"It is|a contradictory that I saw his dog and he does not own a dog"],
[ 82,"It is|a contradictory that his dog drank some water and he does not own a dog"],
[ 83,"It is|a contradictory that I took the dog's ball and the dog does not own a ball"],
[ 84,"It is|a contradictory that the dog's ball is|a red and the dog does not own a ball"],
[ 85,"It is|a contradictory that Ada's ball is|a red and Ada does not own a ball"],
[ 86,"It is|a contradictory that I took Ada's ball and Ada does not own a ball"],
[ 87,"It is|a contradictory that the|r property|n redness is|a red"],
[ 88,"It is|a contradictory that plato has|t the same teacher as Xenothon and Xenothon does not have|t a teacher"],
[ 89,"It is|a contradictory that I did not shed any|n tears and I shed a tear"],
[ 90,"It is|a contradictory that there is|e a thought which smells"],
[ 91,"It is|a contradictory that there is|e a thought which desires something"],
[ 92,"It is|a contradictory that there is|e a mind which is|a not mental"],
[ 93,"It is|a consistent that there is|e a thought which is|g a|r group"],
[ 94,"It is|a contradictory that there is|e a number|i which is|a physical"],
[ 95,"It is|a contradictory that there is|e a mind which smells"],
[ 96,"It is|a contradictory that there is|e a point which smells"],
[ 97,"It is|a contradictory that there is|e a thought which is|a physical"],
[ 98,"It is|a contradictory that there is|e a moment which is|a physical"],
[ 99,"It is|a contradictory that JFK is|g a|r Kennedy and JFK is|g not part|f of the Kennedy|a family"],
[ 100,"It is|a contradictory that something is|g a|r cake and cake is|g not a|r class"],
[ 101,"It is|a contradictory that there is|e a point which thinks some|p thoughts"],
[ 102,"It is|a contradictory that some|p minds smell"],
[ 103,"It is|a contradictory that some|p points smell"],
[ 104,"It is|a contradictory that some|p numbers|i are|a physical"],
[ 105,"It is|a contradictory that some|p points think something"],
[ 106,"It is|a contradictory that some|p points have|w members"],
[ 107,"It is|a contradictory that some|p points are|a physical"],
[ 108,"It is|a contradictory that some|p numbers|i smell"],
[ 109,"It is|a contradictory that some|p thoughts are|a not mental"],
[ 110,"It is|a contradictory that some|p thoughts are|g moments"],
[ 111,"It is|a contradictory that some|p thoughts think something"],
[ 112,"It is|a contradictory that some|p thoughts smell"],
[ 113,"It is|a contradictory that some|p thoughts desire something"],
[ 114,"It is|a contradictory that Russell has|c|r the|r causal role can hit and the|r causal role can hit is|g not a|r property|n"],
[ 115,"It is|a contradictory that a universal is|r not distinct from its|a instance"],
[ 116,"It is|a contradictory that there is|e a universal which is|r not distinct from its|a instances"],
[ 117,"It is|a contradictory that the|r concept|n cat is|g itself|r a|r cat"],
[ 118,"It is|a contradictory that dog is|g not a|r concept|n"],
[ 119,"It is|a contradictory that point is|g a|r partially material|a concept|n"],
[ 120,"It is|a contradictory that this dog is|g a|r concept|n"],
[ 121,"It is|a contradictory that thought is|g a|r partially material|a concept|n"],
[ 122,"It is|a contradictory that there is|e a point which is|a physical"],
[ 123,"It is|a contradictory that there is|e a number|i which smells"],
[ 124,"It is|a contradictory that there is|e a thought which is|a not mental|b"],
[ 125,"It is|a contradictory that there is|e a thought which is|g a|r moment"],
[ 126,"It is|a contradictory that there is|e a thought which thinks something"],
[ 127,"It is|a contradictory that I have a point"],
[ 128,"It is|a contradictory that plato has|t the same teacher as Xenothon and that|d teacher is Socrates and socrates does not teach Xenothon"],
[ 129,"It is|a contradictory that I saw the same movie as you and that|d movie was Casablanca and I did not see Casablanca"],
[ 130,"It is|a contradictory that Leibniz and|c Aristotle ate from the same cake and this|n was that|d cake and Leibniz did not eat from this|n"],
[ 131,"It is|a contradictory that the door is|a not large and the door which is|a green is|a large"],
[ 132,"It is|a contradictory that Leibniz and|c Aristotle studied logic  and Leibniz did not study logic"],
[ 133,"It is|a contradictory that Russell is|g not a|r man"],
[ 134,"It is|a contradictory that Russell has the|r property|n courage  and Russell is|a not courageous"],
[ 135,"It is|a contradictory that Russell has courage  and Russell is|a not courageous"],
[ 136,"It is|a contradictory that this cat is|g not a|r cat"],
[ 137,"It is|a contradictory that JFK is|g not a|r Kennedy and JFK is|g part|f of the Kennedy|a family"],
[ 138,"It is|a contradictory that Julius Caesar is|g a|r number|i"],
[ 139,"It is|a consistent that Julius Caesar is|g not a|r number|i"],
[ 140,"It is|a consistent that I took a dog's ball and there is|e a dog which owns a ball"],
[ 141,"It is|a contradictory that I took a dog's ball and no dog owns a ball"],
[ 142,"It is|a consistent that every mind is|a mental"],
[ 143,"It is|a contradictory that no mind is|a mental"],
[ 144,"It is|a contradictory that a moment is|r greater than a number|i"],
[ 145,"It is|a contradictory that I desire a concept|n"],
[ 146,"It is|a contradictory that the|r concept|n mind is|r in|r this house"],
[ 147,"It is|a contradictory that there is|e a property which is|g an individual"],
[ 148,"It is|a contradictory that the|r property|n redness is|r composed of some|p particles"],
[ 149,"It is|a contradictory that there is|e a concept|n which is|g an|r individual|a thing"],
[ 150,"It is|a contradictory that this|n is|g a|r particular dog  and this|n is the|r concept|n dog"],
[ 151,"It is|a contradictory that redness is|g not a|r particular concept|b and this|n has redness"],
[ 152,"It is|a contradictory that this particular man has|m some|p instances"],
[ 153,"It is|a contradictory that this particular woman is|g not an|r instance|i of the|r concept|n woman"],
[ 154,"It is|a consistent that a moment is|r not greater than a number|i"],
[ 155,"It is|a consistent that I do not desire a concept|n"],
[ 156,"It is|a consistent that the|r concept|n mind is|r not in|r this house"],
[ 157,"It is|a consistent that no property|n is|g an individual"],
[ 158,"It is|a consistent that the|r property|n redness is|r not composed of some|p particles"],
[ 159,"It is|a consistent that no concept|n is|g an|r individual|a thing"],
[ 160,"It is|a consistent that this|n is|g a|r particular dog and this|n is not the|r concept|n dog"],
[ 161,"It is|a consistent that redness is|g a|r particular concept|b and this|n has redness"],
[ 162,"It is|a consistent that this particular man does not have|m some|p instances"],
[ 163,"It is|a consistent that this particular woman is|g an|r instance|i of the|r concept|n woman"],
[ 164,"It is|a contradictory that I did not shed a tear and I did not shed many|n tears"],
[ 165,"It is|a consistent that I shed a tear and I shed many|n tears"],
[ 166,"It is|a contradictory that many|n minds smell"],
[ 167,"It is|a contradictory that many|n points smell"],
[ 168,"It is|a contradictory that many|n numbers|i are|a physical"],
[ 169,"It is|a contradictory that many|n points think something"],
[ 170,"It is|a contradictory that many|n points are|a mental"],
[ 171,"It is|a contradictory that many|n points are|a physical"],
[ 172,"It is|a contradictory that many|n numbers|i smell"],
[ 173,"It is|a contradictory that many|n thoughts are|a not mental"],
[ 174,"It is|a contradictory that I have many|n points"],
[ 175,"It is|a contradictory that I do not have many|n points"]]
    return sent, 356