def large_dict():
    dict2= [['rat','above','AB','((bIc) x^ (dABb)) & ((bIc) x^ (bABe)) & (c=point)'],
['rat','after ','A','((bIc) x^ (dAb)) & ((bIc) x^ (bAe)) & (c=moment)'],
['rat','after|n ','G','((bIc) x^ (dGb)) & ((bIc) x^ (bGe)) & (c=number)'],
['rat','are|a','J','((bJc) x^ (cId)) & ((bJc) t^ (bIe)) & ((bJc) t^ (cIf)) & (d=property) & (e=thing) & (f=adjective)'],
['rat','are|g ','I','((bIc) x^ (cId)) & ((eIf) x^ (eIg)) & (d=concept|n) & (g=instance)'],
['rais','at','S','((bIc) x^ (dSb)) & ((dIf) x^ (dSb)) & (c=point) & (f=particle) '],
['rat','at|i ','M','((dMb) t^ (dIc)) & ((bIf) x^ (dMb)) & (c=relationship) & (f=imagination) '],
['rat','at|n ','N','((bIc) x^ (dNb)) & ((eIf) x^ ((eNh) & (hGg))) & ((jIk) x^ (mNg)) & ((nIo) x^ (nNp)) & (f=whole) & (c=number) & (g=1) & (k=individual) & (p=0) & (o=contradiction) '],
['ratab','at|p ','ATC','((dPb) t^ (dIc)) & ((bIf) x^ (dPb)) & (c=relationship) & (f=possible world) '],
['rais','at|t ','T','((dTb) t^ (dIc)) & ((bIf) x^ (dTb)) & (c=relationship) & (f=moment) '],
['rai','desire','D','((dDb) t^ ((bIc) & (bJe))) & ((bIf) x^ (dDb)) & (c=relationship) & (f=mind) & (e=open|r)'],
['ra','have','H','((bHc) x^ (cId)) & ((bHc) t^ (bIe)) & ((bHc) t^ (cIf)) & (d=property|n) & (e=thing) & (f=noun)'],
['rats','in front of','F','((bIc) x^ (dFb)) & ((bIc) x^ (bFe)) & (c=point)'],
['rats','left of','L','((bIc) x^ (dLb)) & ((bIc) x^ (bLe)) & (c=point)'],
['n','concept|n',None,'(c=concept|n) & ((bIc) x^ (zIb)) & ((bIc) t^ (bIe)) & (e=non_whole)'],
['aa','extant',None,'((bJc) t^ (cId)) & (d=property)'],
['n','instance',None,'(c=instance) & ((bIc) x^ (bId))'],
['n','integer',None,'(c=integer) & ((bIc) x^ (bGd)) & ((bIc) x^ (eGb)) & ((bIc) x^ (fNb)) & ((bIc) t^ (bIg)) & (g=non_whole)'],
['n','mind',None,'(c=mind) & ((bIc) t^ (bTKz))'],
['n','moment',None,'(c=moment) & ((bIc) x^ (dTb)) & ((bIc) x^ (bAh)) & ((bIc) x^ (eAb)) & ((bIc) t^ (bIf)) & (f=non_whole)'],
['na','now',None,'(b=now) t^ (cSb)'],
['n','part',None,'(c=part) & ((bIc) x^ (dWb))'],
['n','particle',None,'(c=particle) & ((bIc) x^ (bSd)) & ((bId) x^ (hTg)) & ((bIc) t^ (bIf)) & (f=non_whole) & (g=now) & (hb^bSd)'],
['n','part|p',None,'(c=part|p) & (((bIc) & (bOFd)) x^ (dWb))'],
['n','point',None,'(c=point) & ((bIc) x^ (dSb)) & ((bIc) x^ (eABb)) & ((bIc) x^ (bABm)) & ((bIc) x^ (fFb)) & ((bIc) x^ (bFj)) & ((bIc) x^ (gLb)) & ((bIc) x^ (bLk)) & ((bIc) t^ (bIh)) & (h=non_whole)'],
['n','property',None,'(c=property) & ((bIc) x^ (dJb)) & ((bIc) t^ (bIe)) & (e=non_whole)'],
['n','property|n',None,'(c=property|n) & ((bIc) x^ (dHb)) & ((bIc) t^ (bIe)) & (e=non_whole)'],
['na','thing',None,'See atomic categories'],
['n','thought',None,'(c=thought) & ((bIc) x^ (dTKb)) & ((bIc) t^ (bIe)) & ((bIc) x^ (bMf)) & (e=relationship)'],
['n','whole',None,'(c=whole) & ((bIc) x^ (bWd))'],
['ns','class',None,'(class = concept|n)'],
['r','exist','EX','(exist=EX) & ((bEX) x^ (bJc)) & (c=extant)'],
['ns','group',None,'(group = whole)'],
['a','material',None,'(c=material) & (d=particle) & ((bJc) x^ (bId))'],
['ns','number|i',None,'(number|i=integer)'],
['as','physical ',None,'(physical=material)'],
['ns','universal',None,'(universal = concept|n)'],
['ra','is','=',''],
['nt','there',None,'(there EX b) x^ (bEX)'],
['na','this|n',None,'(this|n Rc) x^ (bRc)'],
['u','which',None,'(bRc which Qd) x^ ((bRc) & (cQd))'],
['u','who',None,'((bRc who Qd) x^ ((bRc) & (cQd) & (bIe))) & (e=person)'],
['ta','an|r',None,'redundant'],
['ta','a|r',None,'redundant'],
['ta','did',None,'redundant'],
['ta','do',None,'redundant'],
['ta','does',None,'redundant'],
['ta','is|r',None,'redundant'],
['ta','itself|r',None,'redundant'],
['ta','on|r',None,'redundant'],
['ta','same',None,'redundant'],
['ta','the|r',None,'redundant'],
['ta','was|r',None,'redundant'],
['ta','will|r',None,'redundant'],
['ma','~',None,'(~p t^ (pIc)) & (c=relationship) & (qJd) & (qb^p&~p) & (d=contradictory)'],
['c','and|c',None,'(b and|c c R d) x^ (b.cRd)'],
['m','not',None,'(not = ~)'],
['ra','R','R','variable relation'],
['d','a',None,'((a bRc) x^ ((dRc) & (dIb) & (dJe))) & (e=indefinite)'],
['di','any|n',None,'(b~R any|n c) x^ (bR no c)'],
['db','every',None,'(every bRc) x^ ((zIb) t^ (zRc))'],
['de','many|n',None,'(many|n b Rc) x^ (((dWe) x^ ((eRc) & (eIb))) & ((fWg) x^ ((g~Rc) & (gIb))) & (dNh) & (fNj) & (hGj) & (dWm) & (mRc) & (mIb) & (fWo) & (o~Rc) & (oIb))'],
['db','no',None,'(no bRc) x^ ((zIb) t^ (z~Rc))'],
['d','the',None,'((the bRc) x^ ((dRc) & (dIb)))'],
['nsd','anyone',None,'(anyone = every person)'],
['nsd','anything',None,'(anything = every thing)'],
['nsd','everyone',None,'(everyone = every person)'],
['nsd','nothing',None,'(nothing = no thing)'],
['ds','some',None,'(some=a)'],
['ds','some|p',None,'(some|p = many|n)'],
['nsd','something',None,'(something = a thing)'],
['ds','that|d',None,'(that|d=the)'],
['ds','this',None,'(this=the)'],
['p','he',None,'((he Rb) x^ ((cRb) & (cId) & (cJe))) & (c=he) & (d=person) & (e=male)'],
['dc','his',None,'((his bRc) x^ ((dRc) & (dIb) & (eOWNd) & (eIg) & (eJf))) & (f=male) & (g=person) & (e=he)'],
['p','i',None,'((i Rb) t^ (iId)) & (d=person)'],
['de','its|a',None,'((b R its|a c) x^ ((bRd) & (dIc) & (bHMd) & (bJf))) & (f=sexless)'],
['dc','my',None,'((my bRc) x^ ((dRc) & (dIb) & (iOWNd)))'],
['p','you',None,'((you Rb) t^ ((cRb) & (cId))) & (c=you) & (d=person)'],
['dc','your',None,'((your bRc) x^ ((dRc) & (dIb) & (eIf) & (eOWNd))) & (e=you) & (f=person)'],
['ra','about','ABT','postponed'],
['rs','not distinct from',None,'(not distinct from = is)'],
['rdiaa','as','AS','(as=AS) & (((bASc) & (dRb)) x^ (cRb))'],
['na','body|c',None,'(c=body|c) & ((bIc) x^ (((bWd) t^ (dIe)) & (bWf))) & (e=particle)'],
['ra','breaks','BRK','postponed'],
['na','causal role',None,'postponed'],
['ra','cause','CA','((pCAq) x^ ((bRc INMd Te) t^ ((fQg INMj Th) & (dCTGj) & (hSUTe)))) & (pb^bRc INMd) & (qb^fQg INMj)'],
['n','courage',None,'(b=courage) & ((cHb) x^ (cJd)) & (d=courageous)'],
['na','courageous',None,'postponed'],
['n','familial part',None,'(c=familial part) & (((bIc) & (bOFd)) x^ (bId))'],
['na','family',None,'postponed'],
['rs','from|b',None,'(from|b = born|p)'],
['r','has|c|r (causal role)','HCA','((bHCAc) x^ (bCAc)) & ((bHCAc) t^ (bHc))'],
['r','has|m','HM','(have|m=HM) & ((bHMc) x^ (cIb))'],
['r','has|t','HAT','(have|t = HAT) & ((bHATc) x^ (cTCHb))'],
['r','have|t','HAT','(have|t = HAT) & ((bHATc) x^ (cTCHb))'],
['ratab','in','IN','((bINc) x^ ((bId) & (cWb))) & (d=point)'],
['r','in|b','INB','((bINBc) x^ ((cWb) & (bId))) & (d=moment)'],
['aa','indefinite',None,'(b=indefinite) & ((cJb) x^ ((cJj) & ((kzzzc) t^ (k~Jj)) & ((eId) t^ ((fPg) & (nt+fPh))))) & (f b^ e=c) & (cId)'],
['nk','individual',None,'(b=individual) & ((cIb) x^ ((dIe) t^ (d~Ic))) & (e=thing)'],
['r','in|m','INM','(bINMc) x^ (((bWd) x^ ((dSe) & (cWe))) & (bWf) & (fSg) & (hWg))'],
['ra','is|e','EX','((bEX) x^ (bJc)) & (c=extant)'],
['aa','large',None,'postponed'],
['ra','lives','LV','postponed'],
['na','logic',None,'postponed'],
['a','mental',None,'(c=mental) & ((bJc) x^ (bTKd))'],
['a','mental|b',None,'(c=mental) & ((bJc) x^ (dTKb))'],
['na','murder',None,'postponed'],
['n','non_whole',None,'(c=non_whole) & ((bIc) x^ ((dIe) t^ (b~Wd))) & (e=thing)'],
['ra','of','OF','postponed'],
['ra','own','OWN','postponed'],
['ra','owns','OWN','postponed'],
['ns','part|f',None,'(part|f=familial part)'],
['a','partially material|a (property)',None,'(b=partially material|a) & ((cJb) x^ ((dWf) & (fIg) & (dJc) & (dWh) & (hIk))) & ((cIb) t^ (cIe)) & (e=property) & (g=body|c) & (k=mind)'],
['na','party',None,'postponed'],
['n','person',None,'(c=person) & (d=personhood) & ((bIc) x^ (bHd))'],
['n','personhood',None,'(c=personhood) & ((bHc) t^ ((bId) & (zTKw) & (zDx) & (bWz) & (bWy) & (yIe))) & (d=person) & (e=body|c)'],
['na','relationship',None,'(c=relationship) & ((bIc) x^ ((bId) ed^ (bIe))) & ((bIc) x^ (bTf)) & (d=explicit|e relationship|e) & (e=implicit|i relationship|i)'],
['aa','sexless',None,'postponed'],
['nu','time',None,'(b=time) x^ ((eTd) x^ (bWd))'],
['ra','took','TAK','postponed'],
['aa','white',None,'postponed'],
['ns','numbers|i',None,'(numbers|i = integer)'],
['ra','ate from','ATF','postponed'],
['na','ball',None,'postponed'],
['ra','born','BRN','postponed'],
['ra','born|p','BRNP','postponed'],
['ra','broke','BRK','postponed'],
['na','cake',None,'postponed'],
['na','casablanca',None,'postponed'],
['na','cat',None,'postponed'],
['aa','caught',None,'postponed'],
['aa','cold',None,'postponed'],
['nc','dog',None,'(c=dog) & (d=doglike) & ((bIc) x^ (bJd))'],
['ac','doglike',None,'(c=dog) & (d=doglike) & ((bJd) x^ ((bIc) & (bWe) & (bWg) & (eIh) & (gIk))) & (k=mind) & (h=body|c)'],
['na','door',None,'postponed'],
['ra','drank','DRK','postponed'],
['ra','drink','DRK','postponed'],
['ra','drinks','DRK','postponed'],
['na','earth',None,'postponed'],
['ra','eat from','ATF','postponed'],
['n','female',None,'(b=male) & (c=female) & ((dJc) t^ (d~Jb))'],
['aa','green',None,'postponed'],
['na','hamlet',None,'postponed'],
['na','house',None,'postponed'],
['n','kennedy',None,'(b=kennedy) & ((cIb) t^ (bId)) & (d=family)'],
['a','kennedy|a',None,'(b=kennedy|a) & (c=kennedy) & (((eJb) & (fIe)) x^ (fIc))'],
['ra','love','LOV','postponed'],
['na','male',None,'(b=male) & (c=female) & ((dJb) t^ (d~Jc))'],
['n','man',None,'(b=man) & ((cIb) x^ ((cId) & (cJe))) & (d=person) & (e=male)'],
['na','mars',None,'natural'],
['na','movie',None,'postponed'],
['na','munich',None,'postponed'],
['na','nazi',None,'postponed'],
['ra','reads','RD','postponed'],
['a','red',None,'(c=red) & ((bJc) t^ (bINMd))'],
['n','redness',None,'(c=redness) & ((bHc) x^ (bJd)) & (d=red)'],
['aa','rewarded',None,'postponed'],
['ra','saw','SEE','postponed'],
['ra','see','SEE','postponed'],
['na','set theory',None,'postponed'],
['ra','shed','SHD','postponed'],
['r','smell','SME','((bSME) t^ (bJc)) & (c=material)'],
['r','smells','SME','((bSME) t^ (bJc)) & (c=material)'],
['na','speed limit',None,'postponed'],
['ra','spied on','SPD','postponed'],
['ra','spies on','SPD','postponed'],
['ra','studied','STD','postponed'],
['ra','study','STD','postponed'],
['ra','teach','TCH','postponed'],
['na','teacher',None,'postponed'],
['ra','teaches','TCH','postponed'],
['na','tear',None,'postponed'],
['na','van',None,'postponed'],
['na','water',None,'postponed'],
['n','woman',None,'(b=woman) & ((cIb) t^ ((cId) & (cJe))) & (d=person) & (e=female)'],
['ns','instances',None,'(instances=instance)'],
['ns','members',None,'(members=part)'],
['ns','minds',None,'(minds=mind)'],
['ns','moments',None,'(moments=moment)'],
['ns','points',None,'(points=point)'],
['ns','tears',None,'(tears=tear)'],
['ns','thoughts',None,'(thoughts=thought)'],
['nun','ada',None,'((b=ada) t^ ((bIc) & (bId))) & (c=woman) & (d=individual)'],
['nun','aristotle',None,'((b=aristotle) t^ ((bIc) & (bId))) & (c=man) & (d=individual)'],
['nun','jessica',None,'((b=jessica) t^ ((bIc) & (bId))) & (c=woman) & (d=individual)'],
['nun','jfk',None,'((b=jfk) t^ ((bIc) & (bId))) & (c=man) & (d=individual)'],
['nun','jim',None,'((b=jim) t^ ((bIc) & (bId))) & (c=man) & (d=individual)'],
['nun','leibniz',None,'((b=leibniz) t^ ((bIc) & (bId))) & (c=man) & (d=individual)'],
['nun','marilyn',None,'((b=marilyn) t^ ((bIc) & (bId))) & (c=woman) & (d=individual)'],
['nun','plato',None,'((b=plato) t^ ((bIc) & (bId))) & (c=man) & (d=individual)'],
['nun','russell',None,'((b=russell) t^ ((bIc) & (bId))) & (c=man) & (d=individual)'],
['nun','socrates',None,'((b=socrates) t^ ((bIc) & (bId))) & (c=man) & (d=individual)'],
['nun','xenothon',None,'((b=xenothon) t^ ((bIc) & (bId))) & (c=man) & (d=individual)'],
['ra','be|a','J','(be|a=J)'],
['rai','desires','D','(desires=D)'],
['ra','has','H','(has=H)'],
['rai','have|w','W','(have|w=W)'],
['rai','is|a ','J','(is|a=J)'],
['rai','is|g ','I','(is|g=I)'],
['rai','think','TK','(think=TK)'],
['rai','thinks','TK','(thinks=TK)'],
['ra','was','=','(was = =)'],
['ra','was|a','J','(was|a=J)'],
['ra','was|e','EX','(was|e = EX)'],
['ra','was|g','I','(was|g=I)'],
['ns','whole|c (fallacious)',None,'(whole|c = concept|n)'],
[None,None,None,None]]
    return dict2